### PR TITLE
Use Rlock when Get

### PR DESCRIPTION
**Pull request by Laisky**
Use Rlock when Get

### CODE REVIEW

**Comment by kevburnsjr** [comment]
@Laisky I submitted a PR to your branch (https://github.com/Laisky/fast-skiplist/pull/1) which would add a bench test to this PR.

@sean-public Parallel bench test shows latency and throughput improvements of RLock are _very_ significant for concurrent access.
```
name               old time/op    new time/op     delta
IncSet-12             277ns ± 8%      277ns ± 7%       ~     (p=0.780 n=10+10)
IncGet-12             154ns ± 2%      164ns ± 2%     +6.09%  (p=0.000 n=10+10)
DecSet-12             173ns ± 3%      175ns ± 5%       ~     (p=0.724 n=10+10)
DecGet-12             160ns ± 3%      166ns ± 1%     +3.69%  (p=0.000 n=10+9)
IncGetParallel-12     263ns ± 1%       39ns ± 5%    -85.35%  (p=0.000 n=8+10)

name               old speed      new speed       delta
IncSet-12          16.4TB/s ± 9%   16.4TB/s ± 8%       ~     (p=0.780 n=10+9)
IncGet-12          58.9TB/s ± 3%   48.1TB/s ± 2%    -18.31%  (p=0.000 n=10+9)
DecSet-12          40.3TB/s ± 9%   40.4TB/s ± 4%       ~     (p=0.968 n=9+10)
DecGet-12          54.5TB/s ± 2%   45.4TB/s ± 9%    -16.82%  (p=0.000 n=9+10)
IncGetParallel-12  17.0TB/s ± 1%  836.3TB/s ±10%  +4817.85%  (p=0.000 n=8+9)

name               old alloc/op   new alloc/op    delta
IncSet-12             61.0B ± 0%      61.0B ± 0%       ~     (all equal)
IncGet-12             0.00B           0.00B            ~     (all equal)
DecSet-12             61.0B ± 0%      61.0B ± 0%       ~     (all equal)
DecGet-12             0.00B           0.00B            ~     (all equal)
IncGetParallel-12     0.00B           0.00B            ~     (all equal)

name               old allocs/op  new allocs/op   delta
IncSet-12              3.00 ± 0%       3.00 ± 0%       ~     (all equal)
IncGet-12              0.00            0.00            ~     (all equal)
DecSet-12              3.00 ± 0%       3.00 ± 0%       ~     (all equal)
DecGet-12              0.00            0.00            ~     (all equal)
IncGetParallel-12      0.00            0.00            ~     (all equal)
```

**Comment by kevburnsjr** [comment]
Disregard. randSource is only used in Set. 👍 

---

I just noticed this comment in math/rand. ~RLock might not be appropriate.~ 
```
// The default Source is safe for concurrent use by multiple goroutines, but
// Sources created by NewSource are not.
```
https://cs.opensource.google/go/go/+/refs/tags/go1.17.1:src/math/rand/rand.go;l=12

**Comment by sean-public** [comment]
> Parallel bench test shows latency and throughput improvements of RLock are very significant for concurrent access.

If the "new times" listed are using RLock, there's notable performance slowdowns in `IncGet-12` and `DecGet-12`. I wonder why that is?

I know there's no synthetic benchmark for this already extant and, further, all synthetic benchmarks have serious shortcomings, but I believe that in a very common workload with a blend of, say, 20% writes and 80% reads all in parallel, there would be worse performance for writes because they are waiting for all of the pending read locks to free.

Just thinking out loud here 🤔

**Comment by kevburnsjr** [comment]
@sean-public You might actually be right about that...
https://gist.github.com/kevburnsjr/a66c19a16d2ae9d74cd501a8b9b3c6b4
```
cpu: Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
BenchmarkIncSet-12               4232509               277.1 ns/op      15272328.16 MB/s              61 B/op          3 allocs/op
BenchmarkIncGet-12               8680887               163.1 ns/op      53221254.06 MB/s               0 B/op          0 allocs/op
BenchmarkDecSet-12               7107218               179.5 ns/op      39584672.41 MB/s              61 B/op          3 allocs/op
BenchmarkDecGet-12               8546569               166.6 ns/op      51298366.60 MB/s               0 B/op          0 allocs/op
BenchmarkParallel/readpct-0-12           3960511               307.9 ns/op             1 B/op          1 allocs/op
BenchmarkParallel/readpct-20-12          4383126               291.3 ns/op             0 B/op          0 allocs/op
BenchmarkParallel/readpct-50-12          4119375               313.9 ns/op             0 B/op          0 allocs/op
BenchmarkParallel/readpct-80-12          3813206               340.5 ns/op             0 B/op          0 allocs/op
BenchmarkParallel/readpct-100-12        33822919                37.14 ns/op            0 B/op          0 allocs/op
PASS
ok      fast-skiplist   27.501s
```

**Comment by kevburnsjr** [comment]
Results
```
name                     old time/op    new time/op     delta
IncSet-12                   270ns ± 3%      277ns ± 4%       ~     (p=0.151 n=5+5)
IncGet-12                   150ns ± 0%      156ns ± 1%     +3.55%  (p=0.008 n=5+5)
DecSet-12                   172ns ± 4%      171ns ± 3%       ~     (p=1.000 n=5+5)
DecGet-12                   154ns ± 1%      159ns ± 0%     +3.20%  (p=0.008 n=5+5)
Mixed/readpct-0-12          171ns ± 0%      174ns ± 1%     +1.93%  (p=0.008 n=5+5)
Mixed/readpct-20-12         172ns ± 0%      175ns ± 0%     +1.53%  (p=0.008 n=5+5)
Mixed/readpct-50-12         170ns ± 1%      176ns ± 1%     +3.60%  (p=0.008 n=5+5)
Mixed/readpct-80-12         160ns ± 0%      168ns ± 0%     +4.59%  (p=0.008 n=5+5)
Mixed/readpct-100-12        153ns ± 1%      158ns ± 0%     +3.63%  (p=0.008 n=5+5)
Parallel/readpct-0-12       299ns ± 1%      304ns ± 0%     +1.53%  (p=0.008 n=5+5)
Parallel/readpct-20-12      302ns ± 0%      287ns ± 1%     -4.77%  (p=0.008 n=5+5)
Parallel/readpct-50-12      294ns ± 0%      310ns ± 1%     +5.44%  (p=0.008 n=5+5)
Parallel/readpct-80-12      275ns ± 1%      340ns ± 1%    +23.52%  (p=0.008 n=5+5)
Parallel/readpct-100-12     250ns ± 1%       37ns ± 1%    -85.13%  (p=0.008 n=5+5)

name                     old speed      new speed       delta
IncSet-12                17.0TB/s ± 4%   16.7TB/s ± 5%       ~     (p=0.690 n=5+5)
IncGet-12                60.7TB/s ± 2%   51.9TB/s ± 1%    -14.57%  (p=0.008 n=5+5)
DecSet-12                41.1TB/s ± 2%   41.5TB/s ± 3%       ~     (p=0.548 n=5+5)
DecGet-12                57.2TB/s ± 1%   49.9TB/s ± 1%    -12.75%  (p=0.008 n=5+5)
Mixed/readpct-0-12       45.1TB/s ± 1%   41.8TB/s ± 1%     -7.32%  (p=0.008 n=5+5)
Mixed/readpct-20-12      44.4TB/s ± 1%   41.3TB/s ± 0%     -6.97%  (p=0.008 n=5+5)
Mixed/readpct-50-12      46.2TB/s ± 0%   40.7TB/s ± 0%    -11.80%  (p=0.008 n=5+5)
Mixed/readpct-80-12      52.2TB/s ± 1%   44.8TB/s ± 0%    -14.09%  (p=0.008 n=5+5)
Mixed/readpct-100-12     58.9TB/s ± 2%   50.4TB/s ± 1%    -14.56%  (p=0.008 n=5+5)
Parallel/readpct-0-12    13.7TB/s ± 1%   12.8TB/s ± 1%     -6.82%  (p=0.008 n=5+5)
Parallel/readpct-20-12   13.6TB/s ± 1%   14.6TB/s ± 1%     +7.84%  (p=0.008 n=5+5)
Parallel/readpct-50-12   14.1TB/s ± 0%   12.6TB/s ± 2%    -10.47%  (p=0.008 n=5+5)
Parallel/readpct-80-12   16.2TB/s ± 1%   10.7TB/s ± 2%    -34.11%  (p=0.008 n=5+5)
Parallel/readpct-100-12  19.4TB/s ± 1%  879.6TB/s ± 7%  +4433.76%  (p=0.008 n=5+5)

name                     old alloc/op   new alloc/op    delta
IncSet-12                   61.0B ± 0%      61.0B ± 0%       ~     (all equal)
IncGet-12                   0.00B           0.00B            ~     (all equal)
DecSet-12                   61.0B ± 0%      61.0B ± 0%       ~     (all equal)
DecGet-12                   0.00B           0.00B            ~     (all equal)
Mixed/readpct-0-12          1.00B ± 0%      1.00B ± 0%       ~     (all equal)
Mixed/readpct-20-12         0.00B           0.00B            ~     (all equal)
Mixed/readpct-50-12         0.00B           0.00B            ~     (all equal)
Mixed/readpct-80-12         0.00B           0.00B            ~     (all equal)
Mixed/readpct-100-12        0.00B           0.00B            ~     (all equal)
Parallel/readpct-0-12       1.00B ± 0%      1.00B ± 0%       ~     (all equal)
Parallel/readpct-20-12      0.00B           0.00B            ~     (all equal)
Parallel/readpct-50-12      0.00B           0.00B            ~     (all equal)
Parallel/readpct-80-12      0.00B           0.00B            ~     (all equal)
Parallel/readpct-100-12     0.00B           0.00B            ~     (all equal)

name                     old allocs/op  new allocs/op   delta
IncSet-12                    3.00 ± 0%       3.00 ± 0%       ~     (all equal)
IncGet-12                    0.00            0.00            ~     (all equal)
DecSet-12                    3.00 ± 0%       3.00 ± 0%       ~     (all equal)
DecGet-12                    0.00            0.00            ~     (all equal)
Mixed/readpct-0-12           1.00 ± 0%       1.00 ± 0%       ~     (all equal)
Mixed/readpct-20-12          0.00            0.00            ~     (all equal)
Mixed/readpct-50-12          0.00            0.00            ~     (all equal)
Mixed/readpct-80-12          0.00            0.00            ~     (all equal)
Mixed/readpct-100-12         0.00            0.00            ~     (all equal)
Parallel/readpct-0-12        1.00 ± 0%       1.00 ± 0%       ~     (all equal)
Parallel/readpct-20-12       0.00            0.00            ~     (all equal)
Parallel/readpct-50-12       0.00            0.00            ~     (all equal)
Parallel/readpct-80-12       0.00            0.00            ~     (all equal)
Parallel/readpct-100-12      0.00            0.00            ~     (all equal)

```

**Pull request closed without merging**
